[debug] [2023-11-29T18:01:14.454Z] ----------------------------------------------------------------------
[debug] [2023-11-29T18:01:14.454Z] Command:       /usr/local/bin/node /usr/local/bin/firebase deploy
[debug] [2023-11-29T18:01:14.455Z] CLI Version:   12.9.1
[debug] [2023-11-29T18:01:14.455Z] Platform:      darwin
[debug] [2023-11-29T18:01:14.455Z] Node Version:  v18.15.0
[debug] [2023-11-29T18:01:14.456Z] Time:          Wed Nov 29 2023 12:01:14 GMT-0600 (Central Standard Time)
[debug] [2023-11-29T18:01:14.456Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-11-29T18:01:14.457Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2023-11-29T18:01:14.509Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-11-29T18:01:14.510Z] > authorizing via signed-in user (c_ganser@mail.fhsu.edu)
[debug] [2023-11-29T18:01:14.510Z] [iam] checking project finance-tracker-12069 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2023-11-29T18:01:14.510Z] > refreshing access token with scopes: []
[debug] [2023-11-29T18:01:14.510Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-11-29T18:01:14.510Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-11-29T18:01:14.513Z] *** [apiv2] error from fetch(https://firebase-public.firebaseio.com/cli.json, {"headers":{},"method":"GET"}): FetchError: request to https://firebase-public.firebaseio.com/cli.json failed, reason: getaddrinfo ENOTFOUND firebase-public.firebaseio.com
[warn] ⚠  Unable to fetch the CLI MOTD and remote config. 
[debug] [2023-11-29T18:01:14.516Z] Failed to fetch MOTD FirebaseError: Failed to make request to https://firebase-public.firebaseio.com/cli.json
[debug] [2023-11-29T18:01:14.518Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------742828502773456560942437","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: getaddrinfo ENOTFOUND www.googleapis.com
[debug] [2023-11-29T18:01:14.518Z] [iam] error while checking permissions, command may fail: FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2023-11-29T18:01:14.518Z] > refreshing access token with scopes: []
[debug] [2023-11-29T18:01:14.518Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-11-29T18:01:14.518Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-11-29T18:01:14.523Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------786278598993009317743542","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: getaddrinfo ENOTFOUND www.googleapis.com
[debug] [2023-11-29T18:01:14.524Z] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[error] 
[error] Error: Assertion failed: resolving hosting target of a site with no site name or target name. This should have caused an error earlier
[debug] [2023-11-29T18:04:15.344Z] ----------------------------------------------------------------------
[debug] [2023-11-29T18:04:15.345Z] Command:       /usr/local/bin/node /usr/local/bin/firebase deploy
[debug] [2023-11-29T18:04:15.345Z] CLI Version:   12.9.1
[debug] [2023-11-29T18:04:15.345Z] Platform:      darwin
[debug] [2023-11-29T18:04:15.345Z] Node Version:  v18.15.0
[debug] [2023-11-29T18:04:15.355Z] Time:          Wed Nov 29 2023 12:04:15 GMT-0600 (Central Standard Time)
[debug] [2023-11-29T18:04:15.355Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-11-29T18:04:15.356Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2023-11-29T18:04:15.406Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-11-29T18:04:15.407Z] > authorizing via signed-in user (c_ganser@mail.fhsu.edu)
[debug] [2023-11-29T18:04:15.407Z] [iam] checking project finance-tracker-12069 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2023-11-29T18:04:15.407Z] > refreshing access token with scopes: []
[debug] [2023-11-29T18:04:15.407Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-11-29T18:04:15.407Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-11-29T18:04:15.410Z] *** [apiv2] error from fetch(https://firebase-public.firebaseio.com/cli.json, {"headers":{},"method":"GET"}): FetchError: request to https://firebase-public.firebaseio.com/cli.json failed, reason: getaddrinfo ENOTFOUND firebase-public.firebaseio.com
[warn] ⚠  Unable to fetch the CLI MOTD and remote config. 
[debug] [2023-11-29T18:04:15.410Z] Failed to fetch MOTD FirebaseError: Failed to make request to https://firebase-public.firebaseio.com/cli.json
[debug] [2023-11-29T18:04:15.413Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------841983256023946238926127","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: getaddrinfo ENOTFOUND www.googleapis.com
[debug] [2023-11-29T18:04:15.413Z] [iam] error while checking permissions, command may fail: FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2023-11-29T18:04:15.413Z] > refreshing access token with scopes: []
[debug] [2023-11-29T18:04:15.414Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-11-29T18:04:15.414Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-11-29T18:04:15.419Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------174359540765650954290403","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: getaddrinfo ENOTFOUND www.googleapis.com
[debug] [2023-11-29T18:04:15.419Z] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[error] 
[error] Error: Assertion failed: resolving hosting target of a site with no site name or target name. This should have caused an error earlier
[debug] [2023-11-29T18:07:07.558Z] ----------------------------------------------------------------------
[debug] [2023-11-29T18:07:07.559Z] Command:       /usr/local/bin/node /usr/local/bin/firebase hosting:channel:deploy test
[debug] [2023-11-29T18:07:07.559Z] CLI Version:   12.9.1
[debug] [2023-11-29T18:07:07.559Z] Platform:      darwin
[debug] [2023-11-29T18:07:07.560Z] Node Version:  v18.15.0
[debug] [2023-11-29T18:07:07.566Z] Time:          Wed Nov 29 2023 12:07:07 GMT-0600 (Central Standard Time)
[debug] [2023-11-29T18:07:07.566Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-11-29T18:07:07.567Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2023-11-29T18:07:07.616Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-11-29T18:07:07.616Z] > authorizing via signed-in user (c_ganser@mail.fhsu.edu)
[debug] [2023-11-29T18:07:07.616Z] [iam] checking project finance-tracker-12069 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2023-11-29T18:07:07.617Z] > refreshing access token with scopes: []
[debug] [2023-11-29T18:07:07.617Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-11-29T18:07:07.617Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-11-29T18:07:07.619Z] *** [apiv2] error from fetch(https://firebase-public.firebaseio.com/cli.json, {"headers":{},"method":"GET"}): FetchError: request to https://firebase-public.firebaseio.com/cli.json failed, reason: getaddrinfo ENOTFOUND firebase-public.firebaseio.com
[warn] ⚠  Unable to fetch the CLI MOTD and remote config. 
[debug] [2023-11-29T18:07:07.619Z] Failed to fetch MOTD FirebaseError: Failed to make request to https://firebase-public.firebaseio.com/cli.json
[debug] [2023-11-29T18:07:07.622Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------167291722245250201086362","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: getaddrinfo ENOTFOUND www.googleapis.com
[debug] [2023-11-29T18:07:07.622Z] [iam] error while checking permissions, command may fail: FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2023-11-29T18:07:07.622Z] > refreshing access token with scopes: []
[debug] [2023-11-29T18:07:07.622Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-11-29T18:07:07.622Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-11-29T18:07:07.626Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------044020021812069596938198","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: getaddrinfo ENOTFOUND www.googleapis.com
[debug] [2023-11-29T18:07:07.627Z] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2023-11-29T18:07:07.627Z] FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
    at invalidCredentialError (/usr/local/lib/node_modules/firebase-tools/lib/auth.js:144:12)
    at refreshTokens (/usr/local/lib/node_modules/firebase-tools/lib/auth.js:508:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.getAccessToken (/usr/local/lib/node_modules/firebase-tools/lib/apiv2.js:149:22)
    at async Client.addAuthHeader (/usr/local/lib/node_modules/firebase-tools/lib/apiv2.js:140:21)
    at async Client.request (/usr/local/lib/node_modules/firebase-tools/lib/apiv2.js:96:34)
    at async getFirebaseProject (/usr/local/lib/node_modules/firebase-tools/lib/management/projects.js:295:21)
    at async getDefaultHostingSite (/usr/local/lib/node_modules/firebase-tools/lib/getDefaultHostingSite.js:14:21)
    at async Object.requireHostingSite [as fn] (/usr/local/lib/node_modules/firebase-tools/lib/requireHostingSite.js:9:18)
    at async /usr/local/lib/node_modules/firebase-tools/lib/command.js:226:17
[error] 
[error] Error: Failed to get Firebase project finance-tracker-12069. Please make sure the project exists and your account has permission to access it.
